apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      labels:
        app: moleculer-microservice-project
    spec:
      containers:
      - name: my-container
        image: gcr.io/moleculer-microservice-project/image
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
        env:
          - name: PROJECT_ID
            value: moleculer-microservice-project
