apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: moleculer-microservice-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: moleculer-microservice-project
